### PR TITLE
Add Illuminate Container

### PR DESCRIPTION
**Pull request by medilies**
https://packagist.org/packages/illuminate/container

### CODE REVIEW

**Comment by dereuromark** [comment]
This is framework specific, right?
As such wouldnt this be part of https://github.com/chiraggude/awesome-laravel#readme instead?

**Comment by medilies** [comment]
Hi @dereuromark.

No, it isn't specific to Laravel. it can be used independently.

Here is an example where I am using it in a PHP library https://github.com/row-bloom/row-bloom/blob/main/src/RowBloomServiceProvider.php

**Comment by dereuromark** [comment]
Why the "see" link then at the end? Seems not needed I guess.

**Comment by dereuromark** [comment]
I see now, it is part of the split packages of Laravel.
I am not sure if the subcomponents should be listed as such tbh.
There is probably a reason why this wasnt done so far.
See https://github.com/ziadoz/awesome-php/pull/815

**Comment by medilies** [comment]
Both comments aren't convincing enough and may be outdated.

> My main problem with this is that the components themselves isn't well documented, and it's hard/near impossible to use them outside of Laravel.

The container implements PSR-11 and is instantly usable after installing with Composer.

> I agree with @sjelfull. We already have Eloquent in the list, which does work well standalone, and is reasonably documented, I think that's enough here.

The container is documented in a decent way at https://laravel.com/docs/10.x/container. I say decent and not well just because the doc speaks in the context of Laravel.

**Comment by dereuromark** [comment]
What do others think?
I am not so much for duplicating this as separate entry if it is already listed as part of the components.

**Comment by medilies** [comment]
My answers are exclusive to the referenced issue, and I agree that Symfony goes the extra mile of documenting/implementing its components as standalone libraries.

So I guess more opinions will enrich the context of making a final decision. GL :)

**Comment by alexkart** [comment]
I agree with @dereuromark it is not clear from that section of the documentation whether it can or cannot be used separately from Laravel. And there are even no examples of using it as a separate component.

**Comment by dereuromark** [comment]
Closing then, I would suggest they work on documenting their split components/packages.
But as said before: Already listed anyway through the other section.

**Pull request closed without merging**
