### PR TITLE
pint

### PR DESCRIPTION
**Pull request by medilies**
- https://laravel.com/docs/pint
- https://github.com/laravel/pint
- https://packagist.org/packages/laravel/pint

### CODE REVIEW

**Comment by dereuromark** [comment]
I feel like someone should start an awesome list for php Code fixers instead.
Those shouldn't all go to this list.

**Comment by medilies** [comment]
That was my firsr intuition. I searched for a formatters section

**Comment by dereuromark** [comment]
We could start one under the umbrella of this organization. If u want to join in.

**Comment by medilies** [comment]
I'm all in for being an active helper. But is there something that limits the act of reshaping the lists?

**Comment by dereuromark** [comment]
How about this: https://github.com/php-collective/awesome-php-sniffers
We can link this from maybe the main PHP one or even the global awesome one.

It can contain also some I help to maintain:
- https://github.com/php-fig-rectified/psr2r-sniffer
- https://github.com/php-collective/code-sniffer

**Comment by dereuromark** [comment]
Closing in favor of https://github.com/php-collective/awesome-php-sniffers or alike as this is a different dimension.

**Pull request closed without merging**
