### PR TITLE
mjml-php

### PR DESCRIPTION
**Pull request by medilies**
- https://github.com/spatie/mjml-php
- https://freek.dev/2549-convert-mjml-to-html-using-php

### CODE REVIEW

**Review by alexkart — APPROVED** [review]

**Comment by dereuromark** [comment]
I am not sure about the name.
Is it `Spatie Mjml` or what is the naming convention here? The github domain/username usually is not it afaik

**Comment by dereuromark** [comment]
I am not asking about the content nut the presentation in this list

**Comment by dereuromark** [comment]
We still didnt quite figure out what the valid name would be
It looks like it could be `Qferrer Mjml` ?

**Comment by dereuromark** [comment]
You should open against original repo, since it is now maintained again it.

**Pull request closed without merging**
